#! /bin/sh

### BEGIN INIT INFO
# Provides:          vncserver
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     3 4 5
# Default-Stop:      0 1 2 6
# Short-Description: Start vncserver
# Description:       Start vncserver on display :5.
### END INIT INFO

#start a vnc server with user kitrokopter 

case "$1" in
    start)
	su kitrokopter -c "vncserver :5"
	;;
    stop)
	su kitrokopter -c "vncserver -kill :5"
	;;
    restart)
        ## Stop the service and regardless of whether it was
        ## running or not, start it again.
        $0 stop
        $0 start

        # Remember status and be quiet
        ;;
esac
